// .NET, the dot is getting removed

export default [
    "Java",
    "Java Certified",
    "Java Enterprise Certified",
    "Javascript",
    "Node.js",
    "Nodejs",
    "Graphql",
    "Express",
    "EOSIO",
    "EOSIO based blockchains",
    "blockchain",
    "Travis CI",
    "Python",
    "C++",
    "C", // possibly problematic
    "Unity",
    "Html/css",
    "Html",
    "Software",
    "Software Engineer",
    "Microservice",
    "Microservice Architecture",
    "Microservice Architectures",
    "Decentralized",
    "API",
    "iOS",
    "Android",
    "C#",
    "IAP",
    "jquery",
    "sql",
    "microsoft server 2012",
    "a+",
    "a+ certification",
    "hti",
    "net+",
    "mcse",
    "ccna"
]